### ISSUE TITLE
Schreibfehler

### ISSUE THREAD

**Issue by dboth** [Kaleidophon/BARBarA#7]
In deinem Abkürzungsverzeichnis hast du "Pwart of Speech" stehen. Das ist sehr falsch. Schäm dich.

Hochachtungsfoll
D. Both und T. Weidler

**Comment by Kaleidophon** [comment]
Das ist gar nicht mehr aktuell! Schau mal im Branch Writing. 

Tiefneunungsvoll, 
D. Ulmer
